In [1]:
dir

In [2]:
!dir

 Volume in drive C is OS
 Volume Serial Number is 5E8D-0C65

 Directory of C:\Users\Tom\Documents\Source\spring2020-repo

02/19/2020  06:27 PM    <DIR>          .
02/19/2020  06:27 PM    <DIR>          ..
02/19/2020  06:27 PM    <DIR>          .ipynb_checkpoints
02/18/2020  10:48 PM    <DIR>          01
02/19/2020  06:25 PM    <DIR>          02
02/14/2020  06:28 PM    <DIR>          03
02/14/2020  06:28 PM    <DIR>          04
02/14/2020  06:28 PM    <DIR>          05
02/14/2020  06:28 PM    <DIR>          06
02/14/2020  06:28 PM    <DIR>          07
02/14/2020  06:28 PM    <DIR>          08
02/14/2020  06:28 PM    <DIR>          09
02/14/2020  06:28 PM    <DIR>          12
02/14/2020  06:28 PM             5,177 2020-spring-biof509-syllabus.md
02/14/2020  06:28 PM    <DIR>          bin
02/14/2020  06:28 PM         1,076,194 brca_protein_expression.tsv.gz
02/14/2020  06:28 PM                 0 build.err
02/14/2020  06:28 PM             9,503 conf.py
02/14/2020  06:28 PM    <DIR>          docs
02/14/2020  06:28 PM               244 environment.yml
02/14/2020  06:28 PM            72,768 faes300.png
02/14/2020  06:28 PM                58 header.tex
02/14/2020  06:28 PM    <DIR>          help
02/14/2020  06:28 PM               828 index.rst
02/14/2020  06:28 PM             7,275 make.bat
02/14/2020  06:28 PM             7,928 Makefile
02/14/2020  06:28 PM               260 postBuild
02/14/2020  06:28 PM               501 README.md
02/14/2020  06:28 PM            19,878 reference.docx
02/14/2020  06:28 PM    <DIR>          resources
02/14/2020  06:28 PM    <DIR>          syllabus
02/19/2020  06:27 PM                72 Untitled.ipynb
              14 File(s)      1,200,686 bytes
              18 Dir(s)  150,647,246,848 bytes free

In [3]:
conda env list

# conda environments:
#
base                  *  C:\Users\Tom\Anaconda3
spring2020               C:\Users\Tom\Anaconda3\envs\spring2020
test                     C:\Users\Tom\Anaconda3\envs\test
                         C:\Users\Tom\OneDrive - Micro Systems Engineering\Source_Cloud\Machine Learning\BIOF509\env


Note: you may need to restart the kernel to use updated packages.

In [4]:
%ls

 Volume in drive C is OS
 Volume Serial Number is 5E8D-0C65

 Directory of C:\Users\Tom\Documents\Source\spring2020-repo

02/19/2020  06:27 PM    <DIR>          .
02/19/2020  06:27 PM    <DIR>          ..
02/19/2020  06:27 PM    <DIR>          .ipynb_checkpoints
02/18/2020  10:48 PM    <DIR>          01
02/19/2020  06:27 PM    <DIR>          02
02/14/2020  06:28 PM    <DIR>          03
02/14/2020  06:28 PM    <DIR>          04
02/14/2020  06:28 PM    <DIR>          05
02/14/2020  06:28 PM    <DIR>          06
02/14/2020  06:28 PM    <DIR>          07
02/14/2020  06:28 PM    <DIR>          08
02/14/2020  06:28 PM    <DIR>          09
02/14/2020  06:28 PM    <DIR>          12
02/14/2020  06:28 PM             5,177 2020-spring-biof509-syllabus.md
02/14/2020  06:28 PM    <DIR>          bin
02/14/2020  06:28 PM         1,076,194 brca_protein_expression.tsv.gz
02/14/2020  06:28 PM                 0 build.err
02/14/2020  06:28 PM             9,503 conf.py
02/14/2020  06:28 PM    <DIR>          docs
02/14/2020  06:28 PM               244 environment.yml
02/14/2020  06:28 PM            72,768 faes300.png
02/14/2020  06:28 PM                58 header.tex
02/14/2020  06:28 PM    <DIR>          help
02/14/2020  06:28 PM               828 index.rst
02/14/2020  06:28 PM             7,275 make.bat
02/14/2020  06:28 PM             7,928 Makefile
02/14/2020  06:28 PM               260 postBuild
02/14/2020  06:28 PM               501 README.md
02/14/2020  06:28 PM            19,878 reference.docx
02/14/2020  06:28 PM    <DIR>          resources
02/14/2020  06:28 PM    <DIR>          syllabus
02/19/2020  06:27 PM                72 Untitled.ipynb
              14 File(s)      1,200,686 bytes
              18 Dir(s)  150,647,263,232 bytes free

In [5]:
%pwd

'C:\\Users\\Tom\\Documents\\Source\\spring2020-repo'

In [6]:
p = %pwd
p

'C:\\Users\\Tom\\Documents\\Source\\spring2020-repo'

In [7]:
from pathlib import Path
p = Path()

In [10]:
p.home()

WindowsPath('C:/Users/Tom')

In [13]:
p2 = p.absolute()

In [14]:
datafile = p2 / "02/winequality-red.csv"

In [16]:
datafile

WindowsPath('C:/Users/Tom/Documents/Source/spring2020-repo/02/winequality-red.csv')

In [17]:
import pandas as pd

In [19]:
df = pd.read_csv(datafile)

In [20]:
from sklearn import datasets

In [21]:
wine = datasets.load_wine()

In [22]:
wine

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2]),
 'target_names': array(['class_0', 'class_1', 'class_2'], dtype='<U7'),
 'DESCR': '.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 178 (50 in each of three classes)\n    :Number of Attributes: 13 numeric, predictive attributes and the class\n    :Attribute Information:\n \t\t- Alcohol\n \t\t- Malic acid\n \t\t- Ash\n\t\t- Alcalinity of ash  \n \t\t- Magnesium\n\t\t- Total phenols\n \t\t- Flavanoids\n \t\t- Nonflavanoid phenols\n \t\t- Proanthocyanins\n\t\t- Color intensity\n \t\t- Hue\n \t\t- OD280/OD315 of diluted wines\n \t\t- Proline\n\n    - class:\n            - class_0\n            - class_1\n            - class_2\n\t\t\n    :Summary Statistics:\n    \n    ============================= ==== ===== ======= =====\n                                   Min   Max   Mean     SD\n    ============================= ==== ===== ======= =====\n    Alcohol:                      11.0  14.8    13.0   0.8\n    Malic Acid:                   0.74  5.80    2.34  1.12\n    Ash:                          1.36  3.23    2.36  0.27\n    Alcalinity of Ash:            10.6  30.0    19.5   3.3\n    Magnesium:                    70.0 162.0    99.7  14.3\n    Total Phenols:                0.98  3.88    2.29  0.63\n    Flavanoids:                   0.34  5.08    2.03  1.00\n    Nonflavanoid Phenols:         0.13  0.66    0.36  0.12\n    Proanthocyanins:              0.41  3.58    1.59  0.57\n    Colour Intensity:              1.3  13.0     5.1   2.3\n    Hue:                          0.48  1.71    0.96  0.23\n    OD280/OD315 of diluted wines: 1.27  4.00    2.61  0.71\n    Proline:                       278  1680     746   315\n    ============================= ==== ===== ======= =====\n\n    :Missing Attribute Values: None\n    :Class Distribution: class_0 (59), class_1 (71), class_2 (48)\n    :Creator: R.A. Fisher\n    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n    :Date: July, 1988\n\nThis is a copy of UCI ML Wine recognition datasets.\nhttps://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data\n\nThe data is the results of a chemical analysis of wines grown in the same\nregion in Italy by three different cultivators. There are thirteen different\nmeasurements taken for different constituents found in the three types of\nwine.\n\nOriginal Owners: \n\nForina, M. et al, PARVUS - \nAn Extendible Package for Data Exploration, Classification and Correlation. \nInstitute of Pharmaceutical and Food Analysis and Technologies,\nVia Brigata Salerno, 16147 Genoa, Italy.\n\nCitation:\n\nLichman, M. (2013). UCI Machine Learning Repository\n[https://archive.ics.uci.edu/ml]. Irvine, CA: University of California,\nSchool of Information and Computer Science. \n\n.. topic:: References\n\n  (1) S. Aeberhard, D. Coomans and O. de Vel, \n  Comparison of Classifiers in High Dimensional Settings, \n  Tech. Rep. no. 92-02, (1992), Dept. of Computer Science and Dept. of  \n  Mathematics and Statistics, James Cook University of North Queensland. \n  (Also submitted to Technometrics). \n\n  The data was used with many others for comparing various \n  classifiers. The classes are separable, though only RDA \n  has achieved 100% correct classification. \n  (RDA : 100%, QDA 99.4%, LDA 98.9%, 1NN 96.1% (z-transformed data)) \n  (All results using the leave-one-out technique) \n\n  (2) S. Aeberhard, D. Coomans and O. de Vel, \n  "THE CLASSIFICATION PERFORMANCE OF RDA" \n  Tech. Rep. no. 92-01, (1992), Dept. of Computer Science and Dept. of \n  Mathematics and Statistics, James Cook University of North Queensland. \n  (Also submitted to Journal of Chemometrics).\n',
 'feature_names': ['alcohol',
  'malic_acid',
  'ash',
  'alcalinity_of_ash',
  'magnesium',
  'total_phenols',
  'flavanoids',
  'nonflavanoid_phenols',
  'proanthocyanins',
  'color_intensity',
  'hue',
  'od280/od315_of_diluted_wines',
  'proline']}

In [24]:
df = pd.DataFrame(data=wine.data, columns=wine.feature_names)

In [25]:
df

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

In [26]:
df.apply(lambda x: x**2)

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,202.4929,2.9241,5.9049,243.36,16129.0,7.8400,9.3636,0.0784,5.2441,31.8096,1.0816,15.3664,1134225.0
1,174.2400,3.1684,4.5796,125.44,10000.0,7.0225,7.6176,0.0676,1.6384,19.1844,1.1025,11.5600,1102500.0
2,173.1856,5.5696,7.1289,345.96,10201.0,7.8400,10.4976,0.0900,7.8961,32.2624,1.0609,10.0489,1404225.0
3,206.4969,3.8025,6.2500,282.24,12769.0,14.8225,12.1801,0.0576,4.7524,60.8400,0.7396,11.9025,2190400.0
4,175.2976,6.7081,8.2369,441.00,13924.0,7.8400,7.2361,0.1521,3.3124,18.6624,1.0816,8.5849,540225.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,187.9641,31.9225,6.0025,420.25,9025.0,2.8224,0.3721,0.2704,1.1236,59.2900,0.4096,3.0276,547600.0
174,179.5600,15.2881,6.1504,529.00,10404.0,3.2400,0.5625,0.1849,1.9881,53.2900,0.4900,2.4336,562500.0
175,176.0929,18.3184,5.1076,400.00,14400.0,2.5281,0.4761,0.1849,1.8225,104.0400,0.3481,2.4336,697225.0
176,173.4489,6.7081,5.6169,400.00,14400.0,2.7225,0.4624,0.2809,2.1316,86.4900,0.3600,2.6244,705600.0
177,199.6569,16.8100,7.5076,600.25,9216.0,4.2025,0.5776,0.3136,1.8225,84.6400,0.3721,2.5600,313600.0

In [27]:
def square(x: float):
    """ square the input value
     returns x raised to the power of 2"""
    return x**2

In [28]:
# .__annotations__ and .__doc__
df.apply(square)

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,202.4929,2.9241,5.9049,243.36,16129.0,7.8400,9.3636,0.0784,5.2441,31.8096,1.0816,15.3664,1134225.0
1,174.2400,3.1684,4.5796,125.44,10000.0,7.0225,7.6176,0.0676,1.6384,19.1844,1.1025,11.5600,1102500.0
2,173.1856,5.5696,7.1289,345.96,10201.0,7.8400,10.4976,0.0900,7.8961,32.2624,1.0609,10.0489,1404225.0
3,206.4969,3.8025,6.2500,282.24,12769.0,14.8225,12.1801,0.0576,4.7524,60.8400,0.7396,11.9025,2190400.0
4,175.2976,6.7081,8.2369,441.00,13924.0,7.8400,7.2361,0.1521,3.3124,18.6624,1.0816,8.5849,540225.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,187.9641,31.9225,6.0025,420.25,9025.0,2.8224,0.3721,0.2704,1.1236,59.2900,0.4096,3.0276,547600.0
174,179.5600,15.2881,6.1504,529.00,10404.0,3.2400,0.5625,0.1849,1.9881,53.2900,0.4900,2.4336,562500.0
175,176.0929,18.3184,5.1076,400.00,14400.0,2.5281,0.4761,0.1849,1.8225,104.0400,0.3481,2.4336,697225.0
176,173.4489,6.7081,5.6169,400.00,14400.0,2.7225,0.4624,0.2809,2.1316,86.4900,0.3600,2.6244,705600.0
177,199.6569,16.8100,7.5076,600.25,9216.0,4.2025,0.5776,0.3136,1.8225,84.6400,0.3721,2.5600,313600.0

In [29]:
df * 2

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,28.46,3.42,4.86,31.2,254.0,5.60,6.12,0.56,4.58,11.28,2.08,7.84,2130.0
1,26.40,3.56,4.28,22.4,200.0,5.30,5.52,0.52,2.56,8.76,2.10,6.80,2100.0
2,26.32,4.72,5.34,37.2,202.0,5.60,6.48,0.60,5.62,11.36,2.06,6.34,2370.0
3,28.74,3.90,5.00,33.6,226.0,7.70,6.98,0.48,4.36,15.60,1.72,6.90,2960.0
4,26.48,5.18,5.74,42.0,236.0,5.60,5.38,0.78,3.64,8.64,2.08,5.86,1470.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,27.42,11.30,4.90,41.0,190.0,3.36,1.22,1.04,2.12,15.40,1.28,3.48,1480.0
174,26.80,7.82,4.96,46.0,204.0,3.60,1.50,0.86,2.82,14.60,1.40,3.12,1500.0
175,26.54,8.56,4.52,40.0,240.0,3.18,1.38,0.86,2.70,20.40,1.18,3.12,1670.0
176,26.34,5.18,4.74,40.0,240.0,3.30,1.36,1.06,2.92,18.60,1.20,3.24,1680.0
177,28.26,8.20,5.48,49.0,192.0,4.10,1.52,1.12,2.70,18.40,1.22,3.20,1120.0

In [30]:
df ** 2

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,202.4929,2.9241,5.9049,243.36,16129.0,7.8400,9.3636,0.0784,5.2441,31.8096,1.0816,15.3664,1134225.0
1,174.2400,3.1684,4.5796,125.44,10000.0,7.0225,7.6176,0.0676,1.6384,19.1844,1.1025,11.5600,1102500.0
2,173.1856,5.5696,7.1289,345.96,10201.0,7.8400,10.4976,0.0900,7.8961,32.2624,1.0609,10.0489,1404225.0
3,206.4969,3.8025,6.2500,282.24,12769.0,14.8225,12.1801,0.0576,4.7524,60.8400,0.7396,11.9025,2190400.0
4,175.2976,6.7081,8.2369,441.00,13924.0,7.8400,7.2361,0.1521,3.3124,18.6624,1.0816,8.5849,540225.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,187.9641,31.9225,6.0025,420.25,9025.0,2.8224,0.3721,0.2704,1.1236,59.2900,0.4096,3.0276,547600.0
174,179.5600,15.2881,6.1504,529.00,10404.0,3.2400,0.5625,0.1849,1.9881,53.2900,0.4900,2.4336,562500.0
175,176.0929,18.3184,5.1076,400.00,14400.0,2.5281,0.4761,0.1849,1.8225,104.0400,0.3481,2.4336,697225.0
176,173.4489,6.7081,5.6169,400.00,14400.0,2.7225,0.4624,0.2809,2.1316,86.4900,0.3600,2.6244,705600.0
177,199.6569,16.8100,7.5076,600.25,9216.0,4.2025,0.5776,0.3136,1.8225,84.6400,0.3721,2.5600,313600.0

In [31]:
df.values # pulls out a numpy array

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])